baseURL = "https://thomas-bouvier.io/"
languageCode = "en-us"
title = "Thomas Bouvier"
theme = "otomo"

[params]
  logo = "Thomas Bouvier"
  logoSmall = "TB"
  description = "Thomas Bouvier is a data engineer interested in science and technology, open-source software, climate and energy."

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[menu]
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    title = "projects"
    url = "/project/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About me"
    title = "about"
    url = "/about/"
    weight = 0
