baseURL = "https://thomas-bouvier.io/"
languageCode = "en"
title = "Thomas Bouvier"
theme = "otomo"

defaultContentLanguage = "en"

[params]
  logo = "Thomas Bouvier"
  logoSmall = "TB"
  description = "I'm a data engineer who would like to build tools for the greater social good."

[taxonomies]
  tag = "tags"
  category = ""

[languages]
  [languages.en]
    languageName = "EN"
    weight = 1
    [[languages.en.menu.main]]
      identifier = "posts"
      name = "Blog"
      url = "/posts/"
      weight = 1
    [[languages.en.menu.main]]
      identifier = "projects"
      name = "Portfolio"
      url = "/projects/"
      weight = 2
    [[languages.en.menu.main]]
      identifier = "about"
      name = "About me"
      url = "/about/"
      weight = 3
  [languages.fr]
    languageName = "FR"
    weight = 2
    description = "Je suis un ingénieur données qui aimerait construire des outils utiles au plus grand nombre."
    [[languages.fr.menu.main]]
      identifier = "posts"
      name = "Blog"
      url = "/posts/"
      weight = 1
    [[languages.fr.menu.main]]
      identifier = "projects"
      name = "Portfolio"
      url = "/projects/"
      weight = 2
    [[languages.fr.menu.main]]
      identifier = "about"
      name = "À propos"
      url = "/a-propos/"
      weight = 3

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
