baseURL = "https://thomas-bouvier.io/"
languageCode = "en-us"
title = "Thomas Bouvier"
theme = "otomo"

[params]
  logo = "Thomas Bouvier"
  logoSmall = "TB"
  description = "Thomas Bouvier is a data engineer interested in science and technology, open-source software, climate and energy."

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    [[languages.en.menu.main]]
      identifier = "posts"
      name = "Blog"
      title = "posts"
      url = "/post/"
      weight = 1
    [[languages.en.menu.main]]
      identifier = "projects"
      name = "Portfolio"
      title = "projects"
      url = "/project/"
      weight = 1
    [[languages.en.menu.main]]
      identifier = "about"
      name = "About me"
      title = "about"
      url = "/about/"
      weight = 0
  [languages.fr]
    languageName = "Français"
    weight = 2
    [[languages.fr.menu.main]]
      identifier = "posts"
      name = "Blog"
      title = "posts"
      url = "/post/"
      weight = 1
    [[languages.fr.menu.main]]
      identifier = "projects"
      name = "Portfolio"
      title = "projects"
      url = "/project/"
      weight = 1
    [[languages.fr.menu.main]]
      identifier = "about"
      name = "À propos"
      title = "about"
      url = "/about/"
      weight = 0

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
