baseURL = "https://thomas-bouvier.io/"
languageCode = "en-us"
title = "Thomas Bouvier"
theme = "otomo"

defaultContentLanguage = "en"

[params]
  logo = "Thomas Bouvier"
  logoSmall = "TB"
  description = "I'm a data engineer interested in science and technology, open-source software, climate and energy."

[taxonomies]
  tag = "tags"
  category = ""

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    [[languages.en.menu.main]]
      identifier = "posts"
      name = "Blog"
      url = "/posts/"
      weight = 1
    [[languages.en.menu.main]]
      identifier = "projects"
      name = "Portfolio"
      url = "/projects/"
      weight = 2
    [[languages.en.menu.main]]
      identifier = "about"
      name = "About me"
      url = "/about/"
      weight = 3
  [languages.fr]
    languageName = "Français"
    weight = 2
    [[languages.fr.menu.main]]
      identifier = "posts"
      name = "Blog"
      url = "/posts/"
      weight = 1
    [[languages.fr.menu.main]]
      identifier = "projects"
      name = "Portfolio"
      url = "/projects/"
      weight = 2
    [[languages.fr.menu.main]]
      identifier = "about"
      name = "À propos"
      url = "/a-propos/"
      weight = 3

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
