baseURL = "https://thomas-bouvier.io/"
languageCode = "en"
title = "Thomas Bouvier"
defaultContentLanguage = "en"

[module]
  [[module.imports]]
    # project theme as a go module
    path = "github.com/thomas-bouvier/gohugo-theme-otomo"

[params]
  logo = "Thomas Bouvier"
  description = "I'm a data engineer favoring projects that promote the dissemination of information and knowledge."

[taxonomies]
  tag = "tags"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    [[languages.en.menu.main]]
      identifier = "posts"
      name = "Blog"
      url = "/posts/"
      weight = 1
    [[languages.en.menu.main]]
      identifier = "projects"
      name = "Projects"
      url = "/projects/"
      weight = 2
    [[languages.en.menu.main]]
      identifier = "about"
      name = "About me"
      url = "/about/"
      weight = 3
  [languages.fr]
    languageName = "Français"
    weight = 2
    description = "Je suis un ingénieur données privilégiant les projets qui favorisent la libération de l'information et des connaissances."
    [[languages.fr.menu.main]]
      identifier = "posts"
      name = "Blog"
      url = "/posts/"
      weight = 1
    [[languages.fr.menu.main]]
      identifier = "projects"
      name = "Projets"
      url = "/projects/"
      weight = 2
    [[languages.fr.menu.main]]
      identifier = "about"
      name = "À propos"
      url = "/a-propos/"
      weight = 3

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
